# Build Docker container

name: Container Build

on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'Runner version'
        required: true
        default: '2.287.1'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os:
        - ubuntu
        - debian
        - redhat-ubi8

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Container Metadata
        id: container_metadata
        uses: actions/github-script@v4
        with:
          script: |
            core.setOutput('container_tag', `${context.repo.owner}/${{ matrix.os }}-actions-runner:${context.sha}`);
            core.setOutput('datetime', new Date().toISOString());
      
      - name: Build Container
        run: |
          docker build -f ${{ matrix.os }}-actions-runner/Dockerfile -t ghcr.io/${{ steps.container_metadata.outputs.container_tag }} \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            --build-arg CREATED="${{ steps.container_metadata.outputs.datetime }}" \
            --build-arg GH_RUNNER_VERSION="${{ github.event.inputs.runner_version }}" \
            .
        shell: bash
      
      - name: Login GHCR.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish
        run: | 
          docker push ghcr.io/${{ steps.container_metadata.outputs.container_tag }}
